# 
# Synthesis run script generated by Vivado
# 

  set_param general.maxThreads 8
  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -id {Synth 8-3917}  -string {{WARNING: [Synth 8-3917] design AXI_MandelRISC_v1_0 has port m00_axi_wuser[-1] driven by constant 0}}  -suppress 
set_msg_config  -id {Synth 8-3917}  -suppress 
set_msg_config  -id {filemgmt 20-1763}  -suppress 
create_project -in_memory -part xc7z010clg400-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths {
  D:/Xilinx/ip_repo/AXI_MandelRISC_1.0
  D:/Xilinx/ip_repo/edit_AXI_MandelRISC_v1_0.srcs/sources_1/ip
} [current_fileset]

read_ip D:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/async_fifo_32x32/async_fifo_32x32.xci
set_property used_in_implementation false [get_files -all d:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/async_fifo_32x32/async_fifo_32x32_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files D:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/async_fifo_32x32/async_fifo_32x32.xci]

read_verilog -library xil_defaultlib {
  D:/Xilinx/ip_repo/axi_mandelrisc_1.0/hdl/AXI_MandelRISC_v1_0_S00_AXI.v
  D:/Xilinx/ip_repo/axi_mandelrisc_1.0/hdl/AXI_MandelRISC_v1_0_M00_AXI.v
  D:/Xilinx/ip_repo/axi_mandelrisc_1.0/hdl/AXI_MandelRISC_v1_0.v
  D:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/mr_fpga_defines.v
  D:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/timescale.v
  D:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/mandelrisc_defines.v
  D:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/mandelrisc.v
  D:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/generic_fractal_rom.v
  D:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/count_leading_zeroes.v
}
read_xdc D:/Xilinx/ip_repo/edit_AXI_MandelRISC_v1_0.srcs/constrs_1/imports/new/timing.xdc
set_property used_in_implementation false [get_files D:/Xilinx/ip_repo/edit_AXI_MandelRISC_v1_0.srcs/constrs_1/imports/new/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property include_dirs D:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src [current_fileset]
set_property webtalk.parent_dir D:/Xilinx/ip_repo/edit_AXI_MandelRISC_v1_0.cache/wt [current_project]
set_property parent.project_dir D:/Xilinx/ip_repo [current_project]
catch { write_hwdef -file AXI_MandelRISC_v1_0.hwdef }
synth_design -top AXI_MandelRISC_v1_0 -part xc7z010clg400-1
write_checkpoint AXI_MandelRISC_v1_0.dcp
report_utilization -file AXI_MandelRISC_v1_0_utilization_synth.rpt -pb AXI_MandelRISC_v1_0_utilization_synth.pb
