# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/timing.xdc

# IP: D:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/async_fifo_32x32/async_fifo_32x32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}]

# XDC: d:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: d:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: d:/Xilinx/ip_repo/AXI_MandelRISC_1.0/src/async_fifo_32x32/async_fifo_32x32_ooc.xdc
