# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/timing.xdc

# XDC: new/physical.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_axi_dispctrl_1_1/system_axi_dispctrl_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dispctrl_1_1 || ORIG_REF_NAME==system_axi_dispctrl_1_1}]

# IP: bd/system/ip/system_axi_protocol_converter_0_0/system_axi_protocol_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_protocol_converter_0_0 || ORIG_REF_NAME==system_axi_protocol_converter_0_0}]

# IP: bd/system/ip/system_axi_vdma_1_1/system_axi_vdma_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_1 || ORIG_REF_NAME==system_axi_vdma_1_1}]

# IP: bd/system/ip/system_ground_0/system_ground_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ground_0 || ORIG_REF_NAME==system_ground_0}]

# IP: bd/system/ip/system_hdmi_tx_0_0/system_hdmi_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_hdmi_tx_0_0 || ORIG_REF_NAME==system_hdmi_tx_0_0}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_processing_system7_0_axi_periph_2/system_processing_system7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_axi_periph_2 || ORIG_REF_NAME==system_processing_system7_0_axi_periph_2}]

# IP: bd/system/ip/system_vdd_1/system_vdd_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vdd_1 || ORIG_REF_NAME==system_vdd_1}]

# IP: bd/system/ip/system_xlconstant_0_2/system_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_2 || ORIG_REF_NAME==system_xlconstant_0_2}]

# IP: bd/system/ip/system_AXI_MandelRISC_0_0/system_AXI_MandelRISC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_AXI_MandelRISC_0_0 || ORIG_REF_NAME==system_AXI_MandelRISC_0_0}]

# IP: bd/system/ip/system_AXI_MandelRISC_0_0/src/async_fifo_32x32/async_fifo_32x32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}]

# IP: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0}]

# IP: bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_1_0 || ORIG_REF_NAME==system_proc_sys_reset_1_0}]

# IP: bd/system/ip/system_proc_sys_reset_2_0/system_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_2_0 || ORIG_REF_NAME==system_proc_sys_reset_2_0}]

# IP: bd/system/ip/system_AXI_MandelRISC_0_1/system_AXI_MandelRISC_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_AXI_MandelRISC_0_1 || ORIG_REF_NAME==system_AXI_MandelRISC_0_1}]

# IP: bd/system/ip/system_AXI_MandelRISC_0_1/src/async_fifo_32x32/async_fifo_32x32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}]

# IP: bd/system/ip/system_AXI_MandelRISC_0_2/system_AXI_MandelRISC_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_AXI_MandelRISC_0_2 || ORIG_REF_NAME==system_AXI_MandelRISC_0_2}]

# IP: bd/system/ip/system_AXI_MandelRISC_0_2/src/async_fifo_32x32/async_fifo_32x32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}]

# IP: bd/system/ip/system_AXI_MandelRISC_0_3/system_AXI_MandelRISC_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_AXI_MandelRISC_0_3 || ORIG_REF_NAME==system_AXI_MandelRISC_0_3}]

# IP: bd/system/ip/system_AXI_MandelRISC_0_3/src/async_fifo_32x32/async_fifo_32x32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}]

# IP: bd/system/ip/system_AXI_MandelRISC_0_4/system_AXI_MandelRISC_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_AXI_MandelRISC_0_4 || ORIG_REF_NAME==system_AXI_MandelRISC_0_4}]

# IP: bd/system/ip/system_AXI_MandelRISC_0_4/src/async_fifo_32x32/async_fifo_32x32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}]

# IP: bd/system/ip/system_AXI_MandelRISC_0_5/system_AXI_MandelRISC_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_AXI_MandelRISC_0_5 || ORIG_REF_NAME==system_AXI_MandelRISC_0_5}]

# IP: bd/system/ip/system_AXI_MandelRISC_0_5/src/async_fifo_32x32/async_fifo_32x32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}]

# IP: bd/system/ip/system_axi_crossbar_0_0/system_axi_crossbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_crossbar_0_0 || ORIG_REF_NAME==system_axi_crossbar_0_0}]

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0}]

# IP: bd/system/ip/system_AXI_MandelRISC_5_0/system_AXI_MandelRISC_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_AXI_MandelRISC_5_0 || ORIG_REF_NAME==system_AXI_MandelRISC_5_0}]

# IP: bd/system/ip/system_AXI_MandelRISC_5_0/src/async_fifo_32x32/async_fifo_32x32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}]

# IP: bd/system/ip/system_AXI_MandelRISC_5_1/system_AXI_MandelRISC_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_AXI_MandelRISC_5_1 || ORIG_REF_NAME==system_AXI_MandelRISC_5_1}]

# IP: bd/system/ip/system_AXI_MandelRISC_5_1/src/async_fifo_32x32/async_fifo_32x32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}]

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_s00_data_fifo_0/system_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_data_fifo_0 || ORIG_REF_NAME==system_s00_data_fifo_0}]

# IP: bd/system/ip/system_m00_regslice_0/system_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_0 || ORIG_REF_NAME==system_m00_regslice_0}]

# IP: bd/system/ip/system_m01_regslice_0/system_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_0 || ORIG_REF_NAME==system_m01_regslice_0}]

# IP: bd/system/ip/system_m02_regslice_0/system_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m02_regslice_0 || ORIG_REF_NAME==system_m02_regslice_0}]

# IP: bd/system/ip/system_m03_regslice_0/system_m03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m03_regslice_0 || ORIG_REF_NAME==system_m03_regslice_0}]

# IP: bd/system/ip/system_m04_regslice_0/system_m04_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m04_regslice_0 || ORIG_REF_NAME==system_m04_regslice_0}]

# IP: bd/system/ip/system_m05_regslice_0/system_m05_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m05_regslice_0 || ORIG_REF_NAME==system_m05_regslice_0}]

# IP: bd/system/ip/system_m06_regslice_0/system_m06_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m06_regslice_0 || ORIG_REF_NAME==system_m06_regslice_0}]

# IP: bd/system/ip/system_m07_regslice_0/system_m07_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m07_regslice_0 || ORIG_REF_NAME==system_m07_regslice_0}]

# IP: bd/system/ip/system_m08_regslice_0/system_m08_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m08_regslice_0 || ORIG_REF_NAME==system_m08_regslice_0}]

# IP: bd/system/ip/system_m09_regslice_0/system_m09_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m09_regslice_0 || ORIG_REF_NAME==system_m09_regslice_0}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}]

# XDC: bd/system/ip/system_axi_protocol_converter_0_0/system_axi_protocol_converter_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_vdma_1_1/system_axi_vdma_1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_1 || ORIG_REF_NAME==system_axi_vdma_1_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_vdma_1_1/system_axi_vdma_1_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_1 || ORIG_REF_NAME==system_axi_vdma_1_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_vdma_1_1/system_axi_vdma_1_1_ooc.xdc

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_0/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_0/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_0/src/async_fifo_32x32/async_fifo_32x32_ooc.xdc

# XDC: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0}]

# XDC: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0}]

# XDC: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_1_0 || ORIG_REF_NAME==system_proc_sys_reset_1_0}]

# XDC: bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_1_0 || ORIG_REF_NAME==system_proc_sys_reset_1_0}]

# XDC: bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0_ooc.xdc

# XDC: bd/system/ip/system_proc_sys_reset_2_0/system_proc_sys_reset_2_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_2_0 || ORIG_REF_NAME==system_proc_sys_reset_2_0}]

# XDC: bd/system/ip/system_proc_sys_reset_2_0/system_proc_sys_reset_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_2_0 || ORIG_REF_NAME==system_proc_sys_reset_2_0}]

# XDC: bd/system/ip/system_proc_sys_reset_2_0/system_proc_sys_reset_2_0_ooc.xdc

# XDC: bd/system/ip/system_AXI_MandelRISC_0_1/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_1/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_1/src/async_fifo_32x32/async_fifo_32x32_ooc.xdc

# XDC: bd/system/ip/system_AXI_MandelRISC_0_2/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_2/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_2/src/async_fifo_32x32/async_fifo_32x32_ooc.xdc

# XDC: bd/system/ip/system_AXI_MandelRISC_0_3/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_3/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_3/src/async_fifo_32x32/async_fifo_32x32_ooc.xdc

# XDC: bd/system/ip/system_AXI_MandelRISC_0_4/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_4/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_4/src/async_fifo_32x32/async_fifo_32x32_ooc.xdc

# XDC: bd/system/ip/system_AXI_MandelRISC_0_5/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_5/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_0_5/src/async_fifo_32x32/async_fifo_32x32_ooc.xdc

# XDC: bd/system/ip/system_axi_crossbar_0_0/system_axi_crossbar_0_0_ooc.xdc

# XDC: bd/system/ip/system_AXI_MandelRISC_5_0/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_5_0/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_5_0/src/async_fifo_32x32/async_fifo_32x32_ooc.xdc

# XDC: bd/system/ip/system_AXI_MandelRISC_5_1/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_5_1/src/async_fifo_32x32/async_fifo_32x32/async_fifo_32x32.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_fifo_32x32 || ORIG_REF_NAME==async_fifo_32x32}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_AXI_MandelRISC_5_1/src/async_fifo_32x32/async_fifo_32x32_ooc.xdc

# XDC: bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_s00_data_fifo_0/system_s00_data_fifo_0_ooc.xdc

# XDC: bd/system/ip/system_m00_regslice_0/system_m00_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_m01_regslice_0/system_m01_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_m02_regslice_0/system_m02_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_m03_regslice_0/system_m03_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_m04_regslice_0/system_m04_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_m05_regslice_0/system_m05_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_m06_regslice_0/system_m06_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_m07_regslice_0/system_m07_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_m08_regslice_0/system_m08_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_m09_regslice_0/system_m09_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/system/system_ooc.xdc
