#False path constraints for crossing clock domains in the Audio and Display cores.
#Synchronization between the clock domains is handled properly in logic.
#TODO: The following constraints should be changed to identify the proper pins
#      of the cores by their hierarchical pin names. Currently the global clock names are
#      used. Ultimately, it would be nice to have the cores automatically generate them.
#adi_i2s constaints:
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_2]
set_false_path -from [get_clocks clk_fpga_2] -to [get_clocks clk_fpga_0]

#axi_dispctrl constraints:
#Note these constraints require that REFCLK be driven by the axi_lite clock (clk_fpga_0)
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks axi_dispctrl_1_PXL_CLK_O]
set_false_path -from [get_clocks axi_dispctrl_1_PXL_CLK_O] -to [get_clocks clk_fpga_0]

# Set false paths between the MandelRISC and the AXI bus
set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_3]
set_false_path -from [get_clocks clk_fpga_3] -to [get_clocks clk_fpga_1]

set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_1]

set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_3]
set_false_path -from [get_clocks clk_fpga_3] -to [get_clocks clk_fpga_0]

# Declare a two-cycle path through the multiplier:
set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_0/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1

set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_1/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1

set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_2/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1

set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_3/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1

set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_4/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1

set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_5/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1

set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_6/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1

set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/ir_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins {system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins {system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/C}] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_rd_r1_reg/C] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
set_multicycle_path -setup -from [get_pins system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 2
set_multicycle_path -hold -from [get_pins system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/rfile_reg*/RAM*/CLK] -through [get_nets *prod31_h* -hierarchical] -to [get_pins {system_i/AXI_MandelRISC_7/inst/AXI_MandelRISC_v1_0_M00_AXI_inst/mandelrisc1/acc_reg[*]/D}] 1
